### ISSUE TITLE
Is this project still active? I would like to begin using it, if it is not abandoned.

### ISSUE THREAD

**Issue by MountainX** [vanakat/zotero-link#5]
Hello. This looks like a nice project with useful features. I am interested in beginning to use it. However, I notice that they has only ever been one commit (technically 2, but essentially just an initial commit). Nothing has happened after that initial commit, which forces me to ask if the project is still active.

I guess it is easy to understand why I don't want to invest my time and build my obsidian workflow around something that isn't actively developed. Hoping this project is still alive. Look for confirmation please. And thanks for building this.

**Comment by MunGell** [comment]
Hi @MountainX 
I would say this project is rather alive than not. 

The Obsidian part of the linking to Zotero is working for me and I haven't done many changes to it since the initial release.

This plugin is based on ZotServer (also my project), but I am looking forward for the official Zotero server implementation that is expected soon. When it will land I might need to update this plugin (or more so `zotero-bridge` sibling) to make it all work out of the box with Zotero.

refs:

* https://forums.zotero.org/discussion/97980/new-plugin-zotserver-for-local-zotero-integrations#latest
* https://groups.google.com/g/zotero-dev/c/eJ9bdtiCvJE/m/iQqEEQqlAAAJ
* https://github.com/Dominic-DallOsto/zotero-api-endpoint
* https://github.com/zotero/zotero/pull/2842
